runtime: nodejs20
env: standard

instance_class: F2

service: default

env_variables:
  NODE_ENV: "production"
  VITE_API_URL: "https://worksparkaiserver-983563815856.europe-west1.run.app"


handlers:
- url: /.*
  secure: always
  script: auto
