# app.yaml (for your React project)

runtime: nodejs20 # Use a Node.js runtime to get a basic web server

# Handlers define how App Engine routes requests to your files.
handlers:
  # This handler serves the static assets (JavaScript, CSS, images, etc.)
  # that Vite builds. The path might be /assets/ or something similar
  # depending on your vite.config.ts. Check your 'dist' folder after
  # running 'npm run build' to see the correct folder name.
  - url: /assets
    static_dir: dist/assets

  # This is the CATCH-ALL handler. It's crucial for a Single Page App (SPA).
  # It makes sure that any request that doesn't match a static file above
  # (e.g., /profile, /settings/security) serves the main index.html file.
  # This allows React Router to take over and handle the routing on the client-side.
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html