runtime: nodejs20
env: standard

instance_class: F2

service: default

env_variables:
  NODE_ENV: "production"
  VITE_API_URL: "https://api-fexo-1091591355962.us-central1.run.app"


handlers:
- url: /.*
  secure: always
  script: auto
