runtime: nodejs20
env: standard

instance_class: F2

service: default

env_variables:
  NODE_ENV: "production"
  VITE_API_URL: "https://api-dot-fexoai.uc.r.appspot.com"


handlers:
- url: /.*
  secure: always
  script: auto
