steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    # This is the command to run
    entrypoint: 'gcloud'
    timeout: 240s
    # These are the arguments passed to the 'gcloud' command
    # Each part of the command is a separate item in the list
    args: ['run', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY