// src/types/index.ts

export type Attachment = {
  _id: string; 
  fileName: string;
  gcsObjectName: string;
  mimeType: string;
  size: number;
};

// Represents a file generated by the code interpreter
export type FileOutput = {
  fileName: string;
  mimeType: string;
  content: string; // Base64 encoded content
};

export type Message = {
  role: 'user' | 'assistant' | 'tool_code_result' | 'tool_code' | 'tool_search_result' | 'tool_search' | 'tool_doc_extract' | 'tool_doc_extract_result';
  content: string | null;
  attachments?: Attachment[];
  tool_id?: string;
  state?: 'writing' | 'ready_to_execute' | 'executing' | 'completed' | 'error' | 'searching' | 'searched' | 'analyzing' | null;
  thinking?: string;
  fileOutput?: FileOutput;
  fileOutputs?: FileOutput[]; 
  isWaiting?: boolean;
};